# Generated by Django 2.2.1 on 2019-12-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
