# Generated by Django 2.2.1 on 2019-06-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='domain_id',
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
