# Generated by Django 2.2.1 on 2019-12-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerMgmt',
            fields=[
                ('computer_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ou_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
