# Generated by Django 2.2.1 on 2019-12-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computermgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computermgmt',
            old_name='ou_name',
            new_name='domain_container',
        ),
    ]
