# Generated by Django 2.2.1 on 2019-12-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermgmt', '0002_auto_20191212_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerReport',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dn', models.CharField(max_length=255)),
                ('objectClass', models.CharField(max_length=255)),
                ('cn', models.CharField(max_length=255)),
                ('sn', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('instanceType', models.CharField(max_length=255)),
                ('whenCreated', models.CharField(max_length=255)),
                ('whenChanged', models.CharField(max_length=255)),
                ('uSNCreated', models.CharField(max_length=255)),
                ('badPwdCount', models.CharField(max_length=255)),
                ('codePage', models.CharField(max_length=255)),
                ('countryCode', models.CharField(max_length=255)),
                ('badPasswordTime', models.CharField(max_length=255)),
                ('lastLogoff', models.CharField(max_length=255)),
                ('lastLogon', models.CharField(max_length=255)),
                ('primaryGroupID', models.CharField(max_length=255)),
                ('accountExpires', models.CharField(max_length=255)),
                ('logonCount', models.CharField(max_length=255)),
                ('sAMAccountName', models.CharField(max_length=255)),
                ('sAMAccountType', models.CharField(max_length=255)),
                ('objectCategory', models.CharField(max_length=255)),
                ('pwdLastSet', models.CharField(max_length=255)),
                ('userAccountControl', models.CharField(max_length=255)),
                ('isCriticalSystemObject', models.CharField(max_length=255)),
                ('uSNChanged', models.CharField(max_length=255)),
                ('distinguishedName', models.CharField(max_length=255)),
            ],
        ),
    ]
