# Generated by Django 2.2.1 on 2019-12-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermgmt', '0003_computerreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerreport',
            name='description',
            field=models.TextField(),
        ),
    ]
