# Generated by Django 2.2.1 on 2019-12-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computermgmt', '0004_auto_20191220_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerreport',
            name='description',
        ),
    ]
