# Generated by Django 2.2.1 on 2019-12-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computermgmt', '0006_computerreport_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerreport',
            name='description',
        ),
    ]
