# Generated by Django 2.2.1 on 2019-06-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('domain_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrgUnitReport',
            fields=[
                ('ou_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('domain_name', models.CharField(max_length=255)),
                ('distinguished_name', models.CharField(max_length=255)),
                ('when_changed', models.CharField(max_length=255)),
                ('when_Created', models.CharField(max_length=255)),
                ('object_guid', models.TextField()),
                ('zip_code', models.CharField(max_length=100)),
                ('street_Address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('managed_by', models.TextField()),
            ],
        ),
    ]
