# Generated by Django 2.2.1 on 2019-12-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grpmgmt',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('container', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('group_type', models.CharField(max_length=255)),
                ('group_scope', models.CharField(max_length=255)),
                ('mail_id', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
        ),
    ]
