# Generated by Django 2.2.1 on 2019-12-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupmgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grpmembers',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
